const age = 13;
console.log(age);
const name = "Sviatoslav";
console.log(name);
const isStudent = true;
console.log(isStudent);
const myString = "'You are filled with determination'";
console.log(myString);
const myNumber = 5;
const number = myNumber + 10;
console.log(number);
const myNull = null;
console.log(myNull);
